name = "otel-test"
main = "src/index.ts"
compatibility_date = "2023-07-07"
compatibility_flags = [ "nodejs_compat" ]
routes = ["otel.jtest.dev/*"]
workers_dev = false

[[queues.producers]]
  queue = "otel-test"
  binding = "OTELTEST"

# Worker also receives messages from the Queue, named "my-queue".
[[queues.consumers]]
  queue = "otel-test"
  max_batch_size = 100   # Max messages per batch
  max_batch_timeout = 5 # Max seconds to wait before batch is full
  max_retries = 0       # Max retries per batch
  max_concurrency = 1
